/* Generated by cbindgen from src/capi.rs. Do not edit by hand — run
 * scripts/generate_capi_header.sh instead. */

#ifndef DXPDF_CAPI_H
#define DXPDF_CAPI_H



#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * A byte buffer handed back across the C ABI.
 *
 * `cap` travels alongside `len` because [`dxpdf_free_buffer`] reconstructs
 * the exact `Vec<u8>` that produced this buffer via [`Vec::from_raw_parts`],
 * which requires the real allocated capacity — not the buffer's logical
 * length — to hand back to Rust's allocator.
 */
typedef struct DxpdfBuffer {
  uint8_t *data;
  uintptr_t len;
  uintptr_t cap;
} DxpdfBuffer;

/**
 * Converts DOCX bytes to PDF bytes.
 *
 * Reads `docx_len` bytes from `docx_ptr` and converts at `image_dpi` (pass
 * [`dxpdf_default_image_dpi`]'s result for the library default). On success
 * writes the PDF bytes into `*out_pdf` and returns `0`. On failure — a
 * conversion error or a caught panic — writes a message into `*out_error`
 * instead, leaves `*out_pdf` zeroed, and returns a nonzero code.
 *
 * # Safety
 *
 * `docx_ptr` must be null or point to `docx_len` readable, initialized
 * bytes. `out_pdf` and `out_error`, if non-null, must each point to valid,
 * writable storage of the matching type. The buffer written to `*out_pdf`
 * must be released with [`dxpdf_free_buffer`], and the string written to
 * `*out_error` with [`dxpdf_free_error`] — both were allocated by Rust's
 * allocator and must not be passed to a C `free()`.
 */
int32_t dxpdf_convert(const uint8_t *docx_ptr,
                      uintptr_t docx_len,
                      float image_dpi,
                      struct DxpdfBuffer *out_pdf,
                      char **out_error);

/**
 * Frees a buffer returned by [`dxpdf_convert`]'s `out_pdf`. Safe to call on
 * a zeroed buffer (e.g. one left behind by a failed conversion).
 *
 * # Safety
 *
 * `buf` must be a [`DxpdfBuffer`] previously returned by `dxpdf_convert`,
 * unmodified, and must not be freed more than once.
 */
void dxpdf_free_buffer(struct DxpdfBuffer buf);

/**
 * Frees an error string returned by [`dxpdf_convert`]'s `out_error`. A
 * no-op on null.
 *
 * # Safety
 *
 * `err` must be a pointer previously returned by `dxpdf_convert`'s
 * `out_error` (or null), unmodified, and must not be freed more than once.
 */
void dxpdf_free_error(char *err);

/**
 * The library's default embedded-image DPI ([`crate::DEFAULT_IMAGE_DPI`]).
 */
float dxpdf_default_image_dpi(void);

/**
 * The floor `image_dpi` is clamped to ([`crate::MIN_IMAGE_DPI`]).
 */
float dxpdf_min_image_dpi(void);

#endif  /* DXPDF_CAPI_H */
